"""
Golden snapshot tests for the LanguageAdapter refactor (ADR-003 Phase 1).

These tests verify that the adapter refactor produces byte-identical parse_file()
and chunk_file_ast() output compared to the pre-refactor golden snapshots.

Golden snapshots are generated by:
    python tools/capture_snapshots.py

A diff here means the refactor changed observable behavior.
If the change is intentional, regenerate the snapshots and update this note.
NEVER silently accept a diff — a changed FQN or chunk boundary orphans existing indexes.
"""
from __future__ import annotations

import json
import os
import sys

import pytest

_SRC = os.path.join(os.path.dirname(__file__), "..", "src")
sys.path.insert(0, os.path.abspath(_SRC))

_FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
_SNAP_DIR     = os.path.join(_FIXTURES_DIR, "snapshots")
_SRC_DIR      = os.path.join(_FIXTURES_DIR, "src")

FIXTURE_NAMES = ["sample.py", "sample.ts", "sample.js", "sample.tsx", "sample.cs", "sample.cpp"]


def _serialize_parse(result) -> dict:
    symbols = sorted(
        [
            {
                "fqn": s.fqn,
                "kind": s.kind,
                "name": s.name,
                "class_context": s.class_context,
                "start_line": s.start_line,
                "end_line": s.end_line,
            }
            for s in result.symbols
        ],
        key=lambda s: s["fqn"],
    )
    edges = sorted(
        [
            {
                "source_fqn": e.source_fqn,
                "target": e.target,
                "kind": e.kind,
                "resolved_target": e.resolved_target,
            }
            for e in result.edges
        ],
        key=lambda e: (e["source_fqn"], e["target"], e["kind"]),
    )
    symbol_types = sorted(
        [
            {
                "fqn": st.fqn,
                "return_type": st.return_type,
                "params": st.params,
                "type_params": st.type_params,
                "is_async": st.is_async,
                "is_generator": st.is_generator,
            }
            for st in result.symbol_types
        ],
        key=lambda st: st["fqn"],
    )
    return {"symbols": symbols, "edges": edges, "symbol_types": symbol_types}


def _serialize_chunks(chunks) -> list:
    return [
        {
            "scope": c.scope,
            "file": c.file,
            "start_line": c.start_line,
            "end_line": c.end_line,
            "tags": sorted(c.tags),
            "text": c.text,
        }
        for c in chunks
    ]


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_snapshot_matches_golden(name):
    snap_path    = os.path.join(_SNAP_DIR, f"{name}.json")
    fixture_path = os.path.abspath(os.path.join(_SRC_DIR, name))

    if not os.path.exists(snap_path):
        pytest.skip(f"No golden snapshot at {snap_path} — run tools/capture_snapshots.py first")

    if not os.path.exists(fixture_path):
        pytest.skip(f"Fixture source missing: {fixture_path}")

    with open(snap_path, encoding="utf-8") as fh:
        golden = json.load(fh)

    with open(fixture_path, encoding="utf-8") as fh:
        content = fh.read()

    from ast_chunker import chunk_file_ast, parse_file

    parse_result = parse_file(fixture_path, content)
    chunks       = chunk_file_ast(fixture_path, content)

    current = {
        "fixture": name,
        "parse":   _serialize_parse(parse_result),
        "chunks":  _serialize_chunks(chunks),
    }

    assert current == golden, (
        f"\nSnapshot mismatch for {name}.\n"
        "If this is an intentional change, regenerate with:\n"
        "    python tools/capture_snapshots.py\n"
        "NEVER silently accept a diff — a changed FQN or chunk boundary orphans existing indexes."
    )
