"""
Golden snapshot tests for the LanguageAdapter refactor (ADR-003 Phase 1).

These tests verify that the adapter refactor produces byte-identical parse_file()
and chunk_file_ast() output compared to the pre-refactor golden snapshots.

Golden snapshots are generated by:
    python tools/capture_snapshots.py

A diff here means the refactor changed observable behavior.
If the change is intentional, regenerate the snapshots and update this note.
NEVER silently accept a diff — a changed FQN or chunk boundary orphans existing indexes.
"""
from __future__ import annotations

import json
import os
import sys

import pytest

_SRC = os.path.join(os.path.dirname(__file__), "..", "src")
sys.path.insert(0, os.path.abspath(_SRC))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tools"))

from capture_snapshots import FIXTURE_NAMES, snapshot  # noqa: E402

_FIXTURES_DIR = os.path.join(os.path.dirname(__file__), "fixtures")
_SNAP_DIR     = os.path.join(_FIXTURES_DIR, "snapshots")
_SRC_DIR      = os.path.join(_FIXTURES_DIR, "src")


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_snapshot_matches_golden(name):
    snap_path    = os.path.join(_SNAP_DIR, f"{name}.json")
    fixture_path = os.path.abspath(os.path.join(_SRC_DIR, name))

    if not os.path.exists(snap_path):
        pytest.skip(f"No golden snapshot at {snap_path} — run tools/capture_snapshots.py first")

    if not os.path.exists(fixture_path):
        pytest.skip(f"Fixture source missing: {fixture_path}")

    with open(snap_path, encoding="utf-8") as fh:
        golden = json.load(fh)

    # The snapshot is built by the capture script itself, so the two cannot drift, and
    # its paths are the bare fixture name, so it matches on any machine and OS.
    current = snapshot(fixture_path, name)

    assert current == golden, (
        f"\nSnapshot mismatch for {name}.\n"
        "If this is an intentional change, regenerate with:\n"
        "    python tools/capture_snapshots.py\n"
        "NEVER silently accept a diff — a changed FQN or chunk boundary orphans existing indexes."
    )
